BEGIN
	OUTPUT BLUE;
	OUTPUT "Tolstoy Vigilance"
	OUTPUT NEWLINE;
	OUTPUT MAGENTA;
	OUTPUT "(C) Copyright 2026 Larry B. Daniel, Atlanta Ga."
	OUTPUT NEWLINE;
	OUTPUT "Maximum return / Minimum effort spent / Perfect leverage found"
	OUTPUT NEWLINE;
	OUTPUT CLEAR;

	INTEGER RND;
	INTEGER ACCUMULATOR;
	INTEGER APPLY;

	INTEGER OUT;
	OUT := 25000;

	INTEGER COMMUNIST; 
	COMMUNIST := 153;

 	INTEGER CHARITY; 
	CHARITY := 85;

S0:	YIELD;
	ACCUMULATOR := 0;

S1:	YIELD;
	
	RND := RANDOM;
	IF RND < 1 THEN RND := 0; 
	RND := RND % 9;
	IF RND = 0 THEN RND := 9;

	IF ACCUMULATOR = 100 THEN JUMP S2; 
	IF ACCUMULATOR = 150 THEN JUMP S3; 
	IF RND = 1 THEN	ACCUMULATOR := 100;
	JUMP S1;

S2:	IF RND = 5 THEN ACCUMULATOR := 150;
	JUMP S1;

S3:	IF RND = 3 THEN ACCUMULATOR := COMMUNIST;

	IF ACCUMULATOR = COMMUNIST THEN 
	BEGIN
		APPLY := 0; TIMED OUT ;
		APPLY := CHARITY; TIMED OUT ;
		APPLY := 0; TIMED OUT ;
	END
	JUMP S0;
END