BEGIN
	INTEGER RND;
	INTEGER ACCUMULATOR;
	INTEGER APPLY;

	INTEGER COMMUNIST; 
	COMMUNIST := 153;

	INTEGER LOVE;
	LOVE := 66;

	INTEGER JOY;
	JOY := 43;

	INTEGER PEACE;
	PEACE := 98;

	ACCUMULATOR := 0;

S1:	RND := RANDOM;
	IF RND < 1 THEN RND := 0; 
	RND := RND % 9;
	IF RND = 0 THEN RND := 9;

	IF ACCUMULATOR = 100 THEN JUMP S2; 

	IF ACCUMULATOR = 150 THEN JUMP S3; 

	IF RND = 1 THEN BEGIN 
		ACCUMULATOR := 100;
		YIELD ;
		JUMP S1;
	END
	YIELD;
	JUMP S1;

S2:	IF RND = 5 THEN BEGIN
		ACCUMULATOR := 150;
		YIELD ;
		JUMP S1;
	END
	YIELD;
	JUMP S1;

S3:	IF RND = 3 THEN ACCUMULATOR := COMMUNIST;

	IF ACCUMULATOR = COMMUNIST THEN 
	BEGIN
		APPLY := 0; YIELD ;
		APPLY := LOVE; YIELD ;
		APPLY := 0; YIELD ;
		APPLY := JOY; YIELD;
		APPLY := 0; YIELD ;
		APPLY := PEACE; YIELD;
		APPLY := 0; YIELD ;
		ACCUMULATOR := 0;
	END
	YIELD;
	JUMP S1
END